version: 2.1
orbs:
  pfe: stevector/pantheon-frontend@dev:scaffold-discrete-commands
workflows:
  build_deploy_test:
    jobs:
      - pfe/gatsby-build-and-deploy:
          use_yarn: false
          deployment_path: docs
          pre-steps:
            - checkout
            - run:
                name: Import Functions and Variables
                command: .circleci/scripts/set-env.sh && source $BASH_ENV
            - run:
                name: Install PHP
                command: sudo apt-get install -y php-cli php-xml
            - run:
                name: Install Terminus
                command: |
                  php .circleci/scripts/terminus-installer.php
            - run:
                name: Import Tokens
                command: gatsby-tokens
            - run:
                name: Import External Data
                command: .circleci/scripts/import-external-data.sh
          post-steps:
            - run:
                name: Check for merge conflicts
                command: .circleci/scripts/merge_conflicts.sh
            - run:
                name: post deployment completion status
                command: |
                  curl "http://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/statuses/$CIRCLE_SHA1" -H "Authorization: token $GITHUB_TOKEN" -X POST -d '{"state": "success", "context": "pantheon/deployment", "description": "Deployment complete", "target_url": "http://'${TERMINUS_ENV}'--'${TERMINUS_SITE}'.my.pantheonfrontend.website/"}'
            - run:
                name: Test links
                command: .circleci/tests/link-checker.sh "http://${TERMINUS_ENV}--${TERMINUS_SITE}.my.pantheonfrontend.website/docs"
            # @todo, add lighthouse, master deployment etc.
